# Generated by Django 4.1.2 on 2022-11-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('short_content', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=500)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(max_length=10)),
            ],
        ),
    ]
